version: "3"

services:
  db:
    image: postgres
    # networks:
    #     - webnet
  web:
    image: django-web
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "8000:8000"

# networks:
#     webnet:
