version: "3"
services:
  consumer:
    build: ./consumer
    command: python3 /app/consumer/recieve.py
    working_dir: /app/consumer
    depends_on:
      - db
      - queue
    volumes:
      - ./consumer:/app/consumer

  producer:
    build: ./producer
    command: python3 /app/producer/send.py
    working_dir: /app/producer
    depends_on:
      - db
      - queue
    volumes:
      - ./producer:/app/producer

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=db
      - POSTGRES_NAME=db
      - POSTGRES_PASSWORD=db


  queue:
    image: rabbitmq:latest
    ports:
      - 5672:5672
